branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      enforce_admins: true
      restrictions:
        users: [] # admins pueden hacer push, otros no
        teams: [] # puedes agregar equipos si lo deseas
      required_status_checks:
        strict: true
        contexts: []
      allow_deletions: false
      allow_force_pushes: false
      required_linear_history: true
      block_creations: false
