services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: mastidea-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: mastidea
      POSTGRES_PASSWORD: mastidea_dev_password
      POSTGRES_DB: mastidea_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mastidea"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: mastidea-qdrant-dev
    restart: unless-stopped
    ports:
      - "6335:6333"
      - "6336:6334"
    volumes:
      - qdrant_dev_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local
  qdrant_dev_data:
    driver: local

networks:
  default:
    name: mastidea-dev-network
